name: Build

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ master ]

jobs:
  build-Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.16"
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: Sync
      run: uv sync
    - name: Build with PyInstaller
      run: uv run pyinstaller deploy/voyager.spec
    - name: Building installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "deploy/Installer.iss"
      shell: cmd
    - uses: actions/upload-artifact@v4
      with:
        name: Voyager-Installer-Windows
        path: deploy/setup/voyagerSetup.exe

  build-Linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Sync
        run: uv sync
      - name: Wheel
        run: uv build --wheel
      - name: Build with PyInstaller
        run: |
          uv run pyinstaller deploy/voyager_onefile.spec
      - uses: actions/upload-artifact@v4
        with:
          name: Voyager-Ubuntu
          path: dist/

  release:
    needs: [build-Windows, build-Linux]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Voyager-Ubuntu/voyager
            Voyager-Ubuntu/*.whl
            Voyager-Installer-Windows/voyagerSetup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}